### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by pocc** [sipcapture/hep-wireshark#11]
As this is a derivative work of Wireshark, you need to use a GPL2-compatible license (see https://wiki.wireshark.org/Lua).

**Comment by lmangani** [comment]
Hi @pocc 

They are indeed: https://github.com/sipcapture/hep-wireshark/blob/710c728be3507d4b2be925de82b30e5cc10f4dac/lua/hep.lua#L7

**Comment by lmangani** [comment]
Closing as I believe we don't really need a `LICENSE` file for the entire repository in order to be compliant. The LUA scripts themselves are very explicitly released under GPLv2 as they should be. 

Feel free to comment if you have better suggestions and thanks for bringing this up, much appreciated! :)

**Comment by pocc** [comment]
My bad. I was looking for it at root level.

Cheers and cool project!

**Comment by lmangani** [comment]
Thanks @pocc for checking and again thanks, always better be safe than sorry! :)
